# Golang CircleCI 2.0 configuration file
#
# This is used to install the latest version of 
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4
    working_directory: ~/repo
    steps:
      - checkout
      - run: sudo apt-get install hugo
      - run: pip install awscli
workflows:
  version: 2
  build:
    jobs:
      - build:
          context: org-global
          filters:
            branches:
              only: master