# Golang CircleCI 2.0 configuration file
#
# This is used to install the latest version of 
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4
        environmnet:
          HUGO_URL: https://github.com/gohugoio/hugo/releases/download/v0.34/hugo_0.34_Linux-64bit.deb
          HUGO_DEB: hugo_0.34_Linux-64bit.deb
    working_directory: ~/repo
    steps:
      - checkout
      - run: curl -O $HUGO_URL
      - run: sudo dpkg -i $HUGO_DEB
      - run: hugo version
      - run: pip install awscli
workflows:
  version: 2
  build:
    jobs:
      - build:
          context: org-global
          filters:
            branches:
              only: master