version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4
    working_directory: ~/repo
    steps:
      - checkout
      - run: wget https://github.com/gohugoio/hugo/releases/download/v0.34/hugo_0.34_Linux-64bit.deb
      - run: sudo dpkg -i hugo_0.34_Linux-64bit.deb
      - run: pip install awscli --upgrade --user
      - run: scripts/deploy.sh
workflows:
  version: 2
  build:
    jobs:
      - build:
          context: org-global
          filters:
            branches:
              only: master
